# Generated by Django 2.2.16 on 2020-10-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiresortpage',
            name='top_destination_first_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ski_resort_pages_top_destination_first_block', to='home.HomePage'),
        ),
    ]
