# Generated by Django 2.2.16 on 2020-09-09 10:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubmodel',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
