# Generated by Django 2.2.12 on 2020-08-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_background_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Imagem de fundo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_body_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Corpo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_title_en',
            field=models.CharField(max_length=16, null=True, verbose_name='Título'),
        ),
    ]
