# Generated by Django 2.2.16 on 2020-09-09 10:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subsubmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubmodel',
            name='body_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubmodel',
            name='body_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubmodel',
            name='body_pt',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
