# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hompageinline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hompageinline',
            name='body_es',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='hompageinline',
            name='body_fr',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='hompageinline',
            name='body_pt',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='hompageinline',
            name='title_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hompageinline',
            name='title_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hompageinline',
            name='title_pt',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
